### ISSUE TITLE
FB/FR: date, time and dateTime controls in XBL

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2295]
Currently these controls are implemented natively in the XForms engine, and is spread around:
- `XFormsInputControl.scala`
- `XFormsInputHandler.scala`
- `xforms.js`
- `calendar.coffee`

The logic associated with these controls can be complex, and making changes can be difficult. In addition, some of the code is pretty old, including using YUI code on the JS side. I would be more flexible to write these controls with XBL.

One showstopper for doing this completely generically is that the XForms engine doesn't support dynamically switching components (#1248). But this is not an issue for Form Builder (#1264). So in the context of Form Builder, we could have these controls bound to, e.g.:

``` css
xf|input:xxf-type('xs:date')
```

Next steps:
- [ ] explore writing a custom `xf|input:xxf-type('xs:date')`
  - should rely on nested `xf:input`? if so, ability to force plain input (instead of XForms engine imposing its own built-in control)
- [ ] switch to non-YUI date picker (see also #1599)

See related [community thread](http://discuss.orbeon.com/Format-input-date-type-td4660150.html).

**Comment by ebruchez** [comment]
One more reason to do this: implementing #2084, Chrome on Android adds arrows to date selectors in the fields, which conflicts with the background calendar icon we place within the field. If we implemented the icon as a "suffix" a la Bootstrap, this could be avoided.

**Comment by ebruchez** [comment]
Noticing #481, an older issue about doing this in XForms. So let this current issue be about doing it without dynamic bindings, and so for Form Builder/Form Runner only, while #481 would be for the lower-level XForms version (if we care about that).

**Comment by ebruchez** [comment]
Components to handle:

- [ ] `fr:date`
- [ ] `fr:time`
- [x] `fr:dateTime` (done with #2221)

**Comment by avernet** [comment]
We've created #3657 to cover the specific case of dates. So, this issue is a superset of #3657.

**Comment by avernet** [comment]
Now handled as part of the work done for #3657 (we still have some issues left to fix; they are listed in that issue, hence that issue is left open for now).
