### ISSUE TITLE
Server not to send back to client known value

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2442]
Use case:

1. User changes the value of an input.
2. Client sends new value to the server.
3. Server sends back new value to the client.

Step 3 is unnecessary, since the client already knows the value, and this calls for not doing so.

This (of course), doesn't cover cases where the value changes and the new value isn't known to the client (e.g. action doing an `xf:setvalue`). 

In cases when something else changes on the control, the value is still sent back (e.g. relevance), as the our XML format doesn't allow us to send just a change in, say, relevance without the value.

Before doing this change, we should think of there are cases where sending back the value would be necessary. We haven't identified any as of this writing.

**Comment by ebruchez** [comment]
What we do now when processing events on the server:

- collect all received value change events from the client
- in `ControlsComparator.scala`, we have the following comment: "Force a change for controls whose values changed in the request"

So that's how it's happening, and it's done explicitly! The question is why do we do this. We could easily turn it off to see what happens. What do you think @avernet?

**Comment by avernet** [comment]
@ebruchez Yes, let's try to turn this off, and see what problems that causes, if any.

**Comment by ebruchez** [comment]
Ok, done. If it works out, remove the code which passes these values down to `ControlsComparator.scala`.

**Comment by avernet** [comment]
@ebruchez Could it be that fa45993a7e3e921baaef9c9742bdcd3f3678bc4d discussed above is causing the test *xf:setvalue to same initial value* to fail? We wouldn't want the server to send back to the client a value the client knows about, but a click that runs a `xf:setvalue` wouldn't fall in that category.

**Comment by ebruchez** [comment]
@avernet Yes, I just updated that test.

**Comment by ebruchez** [comment]
Ok, it turns out we have to revert these changes. We now understand why we implemented this:

- say server and client are in sync, and the state of controls on the server is S1
- client changes the value of 2 fields F1 and F2, and the change events reach the server
- server processes events and produces state S2
- server diffs S1 and S2 and sends diff to client BUT also sends the current values of F1 and F2, say F1' and F2', because the diff of S1 and S2 doesn't yet include the changes to F1 and F2 known to the client

This will cause the server to always tell the client about the current value of F1 and F2, even if F1 != F1' or F2 != F2'. This is not wrong, but not optimal.

Ideally, we would like the server to create a state S1' taking the values of F1 and F2. This represents the latest state of the client known to the server. Then diffing S1' and S2 would be enough and provide a more optimal diff.

**Comment by ebruchez** [comment]
Current status: we leave things as they are as the server's response is not wrong. @avernet to check whether there was a case where this would cause problem for a given XBL component.

**Comment by ebruchez** [comment]
One issue: if there is any other difference on a control, such as going from not visited to visited, or a change in MIP, we resend the value of the control as well. So in such cases, the issue would remain.

Example:

```xml
<xxf:control id="details-section≡xf-391≡author-control" visited="true">Stella</xxf:control>
```

The problem is that we don't have a way, in the response format, to say to ignore the value. Maybe we should do something like this:

```xml
<xxf:control id="details-section≡xf-391≡author-control" visited="true" novalue="true"/>
```

**Comment by avernet** [comment]
True, and I can see this happening if a required field becomes valid because a value has now been provided. So with a solution for this, the problem could still show up pretty quickly.

**Comment by ebruchez** [comment]
- [ ] complete changes to `AjaxServer.js` and `xforms.js` to process `xxf:value`
- [ ] update `xforms-server-response.rng`
- [ ] update `XFormsSingleNodeControl` and subclasses to output `xxf:value` and handle original value
- [ ] check what we do when a control becomes non-relevant (We should not include a value either. Do we?)
