### ISSUE TITLE
Database reindex not working with v1 of the form

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4502]
Not sure if all steps are needed:

1. create and publish form as version 1, making form available
2. also publish form as version 2, making form available
3. republish version 2, making form unavailable
4. create and save data for v1 of form
5. Summary page shows 1 entry
6. in Form Builder, make one more more fields Show in Summary/Search
7. republish version 1, making form available
8. Summary page shows 1 entry and field columns, but no data in columns
9. go to Home Page as admin, and Reindex Database
10. Summary page shows 1 entry and field columns, but still no data in columns

Could it be that the reindex operation doesn't reindex all versions?

**Comment by avernet** [comment]
During step 7 above, I am getting the following error (`4502/a` is my app/form name):

    Duplicate entry '4502-a-1' for key 'orbeon_form_definition_i1'

Apparently I had locally a unique index on `orbeon_form_definition` for `app/form/version`, which is incorrect. In our DDL, this index is not unique, and just on `app/form`. I updated my local index accordingly.

**Comment by avernet** [comment]
I'm unable to reproduce this one. At step 8, I do see the 2nd column, and the 1st column is properly populate with the data from before I published the form with the new field. And after reindexing (step 9), the value is still there.

**Comment by avernet** [comment]
I'm still unable to reproduce this on `demo.orbeon.com`. On step 8, the summary page does show 2 columns, with the proper data for the first field:

<img width="955" alt="image" src="https://user-images.githubusercontent.com/106961/82080159-e5092a80-9698-11ea-847c-59431f020033.png">

**Comment by ebruchez** [comment]
I tried this, and:

- locally, I don't reproduce the problem, and the reindexing populates the data in the Summary page
- on prod.orbeon.com, with exactly the same steps, I reproduce the problem

Interestingly enough, the "Reindex database" operation, locally shows some progress before saying that it is "finished", while on prod, it terminated almost immediately. I don't see any error in the logs.

It would be interesting to set our main branch on, say, beta.orbeon.com, to see if the problem shows there.

**Comment by ebruchez** [comment]
I installed the lastest master against the prod database and unfortunately, this still doesn't work. I suspect that the reindexing doesn't do anything but I could be wrong.

**Comment by ebruchez** [comment]
Next step: export MySQL database for @avernet  to run locally.

**Comment by avernet** [comment]
Fixed by https://github.com/orbeon/orbeon-forms-pe/commit/2de6931aa1f7b8b3b2fed762c1b658449fd555a9.
